// GERADO por scripts/gerar-dicionario-caracteristicas.mjs — não editar à mão.
// Dicionário de características EXCLUSIVO da MoldSystems/Innove (625 entradas).
export interface EntradaDicionario {
  chave: string
  rotulo: string
}

export const ROTULOS: Record<number, EntradaDicionario> = {
  1: { chave: "area-construida", rotulo: "Área construída" },
  2: { chave: "area-total", rotulo: "Área total" },
  3: { chave: "frente", rotulo: "Frente" },
  4: { chave: "fundos", rotulo: "Fundos" },
  5: { chave: "dormitorios", rotulo: "Dormitórios" },
  6: { chave: "sendo-dormitorios-suites", rotulo: "Sendo dormitórios suítes" },
  7: { chave: "banheiros", rotulo: "Banheiros" },
  8: { chave: "closets", rotulo: "Closets" },
  9: { chave: "copas", rotulo: "Copas" },
  10: { chave: "lavanderias", rotulo: "Lavanderias" },
  11: { chave: "lavabos", rotulo: "Lavabos" },
  12: { chave: "garagens", rotulo: "Garagens" },
  13: { chave: "sendo-garagens-cobertas", rotulo: "Sendo garagens cobertas" },
  14: { chave: "sobrado", rotulo: "Sobrado" },
  15: { chave: "piscina", rotulo: "Piscina" },
  16: { chave: "cozinhas", rotulo: "Cozinhas" },
  17: { chave: "churrasqueiras", rotulo: "Churrasqueiras" },
  18: { chave: "sala-de-jogos", rotulo: "Sala de jogos" },
  19: { chave: "sauna", rotulo: "Sauna" },
  20: { chave: "interfone", rotulo: "Interfone" },
  21: { chave: "dormitorio-funcionario", rotulo: "Dormitório funcionário" },
  22: { chave: "banheiro-funcionario", rotulo: "Banheiro funcionário" },
  23: { chave: "ponto-de-referencia", rotulo: "Ponto de referência" },
  24: { chave: "padrao-de-acabamento", rotulo: "Padrão de acabamento" },
  25: { chave: "estado-de-conservacao", rotulo: "Estado de conservação" },
  26: { chave: "tipo-de-cobertura", rotulo: "Tipo de cobertura" },
  27: { chave: "mobilia", rotulo: "Mobília" },
  28: { chave: "idade-do-imovel", rotulo: "Idade do imóvel" },
  29: { chave: "construcao-averbada", rotulo: "Construção averbada" },
  30: { chave: "tipo-de-acabamento", rotulo: "Tipo de acabamento" },
  31: { chave: "portao-eletronico", rotulo: "Portão eletrônico" },
  32: { chave: "teto-em-laje", rotulo: "Teto em laje" },
  33: { chave: "teto-em-gesso", rotulo: "Teto em gesso" },
  34: { chave: "isolamento", rotulo: "Isolamento" },
  35: { chave: "escriturada", rotulo: "Escriturada" },
  36: { chave: "habite-se", rotulo: "Habite-se" },
  37: { chave: "projeto-aprovado", rotulo: "Projeto aprovado" },
  38: { chave: "inss-pago", rotulo: "INSS pago" },
  39: { chave: "imovel-financiado", rotulo: "Imóvel financiado" },
  40: { chave: "instituicao-de-financiamento", rotulo: "Instituição de financiamento" },
  41: { chave: "valor-condominio", rotulo: "Valor condomínio" },
  42: { chave: "numero-medidor-energia", rotulo: "Número Medidor energia" },
  43: { chave: "numero-medidor-agua", rotulo: "Número Medidor água" },
  44: { chave: "aceita-financiamento", rotulo: "Aceita financiamento" },
  45: { chave: "aceita-carro", rotulo: "Aceita carro" },
  46: { chave: "aceita-imovel", rotulo: "Aceita imóvel" },
  47: { chave: "aceita-parcelamento", rotulo: "Aceita parcelamento" },
  48: { chave: "aceita-permuta", rotulo: "Aceita permuta" },
  49: { chave: "saldo-devedor", rotulo: "Saldo devedor" },
  50: { chave: "valor-prestacao", rotulo: "Valor prestação" },
  51: { chave: "prazo-restante", rotulo: "Prazo restante" },
  52: { chave: "n-do-apartamento", rotulo: "Nº do apartamento" },
  53: { chave: "n-do-andar", rotulo: "Nº do andar" },
  54: { chave: "n-do-bloco", rotulo: "Nº do bloco" },
  55: { chave: "observacoes-condominio", rotulo: "Observações condomínio" },
  56: { chave: "numero-no-condominio", rotulo: "Número no condomínio" },
  57: { chave: "academia", rotulo: "Academia" },
  58: { chave: "area-de-lazer", rotulo: "Área de lazer" },
  59: { chave: "auditorio", rotulo: "Auditório" },
  60: { chave: "campo-de-futebol", rotulo: "Campo de futebol" },
  61: { chave: "centro-de-convivio", rotulo: "Centro de convívio" },
  62: { chave: "cerca-eletrica", rotulo: "Cerca elétrica" },
  63: { chave: "ciclo-faixa", rotulo: "Ciclo Faixa" },
  64: { chave: "deck", rotulo: "Deck" },
  65: { chave: "espaco-de-leitura", rotulo: "Espaço de leitura" },
  66: { chave: "espaco-fitness", rotulo: "Espaço Fitness" },
  67: { chave: "espaco-gourmet", rotulo: "Espaço Gourmet" },
  68: { chave: "espelho-d-agua", rotulo: "Espelho d’água" },
  69: { chave: "gazebo", rotulo: "Gazebo" },
  70: { chave: "mini-campo", rotulo: "Mini campo" },
  71: { chave: "monitoramento-por-cameras", rotulo: "Monitoramento por câmeras" },
  72: { chave: "muro", rotulo: "Muro" },
  73: { chave: "piscina-infantil", rotulo: "Piscina infantil" },
  74: { chave: "pista-de-cooper", rotulo: "Pista de Cooper" },
  75: { chave: "playground", rotulo: "Playground" },
  76: { chave: "portaria-24-hrs", rotulo: "Portaria 24 Hrs" },
  77: { chave: "portaria-de-servico", rotulo: "Portaria de Serviço" },
  78: { chave: "portaria-social", rotulo: "Portaria Social" },
  79: { chave: "quadra-de-tenis", rotulo: "Quadra de tênis" },
  80: { chave: "quadra-gramada", rotulo: "Quadra Gramada" },
  81: { chave: "quadra-poliesportiva", rotulo: "Quadra Poliesportiva" },
  82: { chave: "ronda-diurna", rotulo: "Ronda diurna" },
  83: { chave: "ronda-noturna", rotulo: "Ronda noturna" },
  84: { chave: "salao-de-festas", rotulo: "Salão de Festas" },
  85: { chave: "varanda-gourmet", rotulo: "Varanda Gourmet" },
  86: { chave: "vestiarios", rotulo: "Vestiários" },
  87: { chave: "via-de-acesso", rotulo: "Via de acesso" },
  88: { chave: "zelador", rotulo: "Zelador" },
  89: { chave: "numero-leitura-energia", rotulo: "Número Leitura energia" },
  90: { chave: "numero-leitura-agua", rotulo: "Número Leitura água" },
  91: { chave: "despensas", rotulo: "Despensas" },
  92: { chave: "salas", rotulo: "Salas" },
  93: { chave: "halls", rotulo: "Halls" },
  94: { chave: "teto-em-pvc", rotulo: "Teto em PVC" },
  95: { chave: "area-util", rotulo: "Área Útil" },
  96: { chave: "elevador-de-servico", rotulo: "Elevador de Serviço" },
  97: { chave: "elevador-social", rotulo: "Elevador Social" },
  98: { chave: "dia-de-vencimento-do-condominio", rotulo: "Dia de vencimento do condomínio" },
  99: { chave: "estado-de-conservacao-outros", rotulo: "Estado de conservação outros" },
  100: { chave: "ponto-comercial", rotulo: "Ponto comercial" },
  101: { chave: "isolamento-outros", rotulo: "Isolamento Outros" },
  102: { chave: "recepcoes", rotulo: "Recepções" },
  103: { chave: "pe-direito", rotulo: "Pé Direito" },
  104: { chave: "depositos", rotulo: "Depósitos" },
  105: { chave: "observacao", rotulo: "Observação" },
  106: { chave: "unidade-de-medida", rotulo: "Unidade de Medida" },
  107: { chave: "area-total-rural", rotulo: "Área Total(Rural)" },
  108: { chave: "agua", rotulo: "Água" },
  109: { chave: "alambrado", rotulo: "Alambrado" },
  110: { chave: "baia", rotulo: "Baia" },
  111: { chave: "benfeitorias", rotulo: "Benfeitorias" },
  112: { chave: "benfeitorias-observacao", rotulo: "Benfeitorias Observação" },
  113: { chave: "caixa-d-agua", rotulo: "Caixa d'água" },
  114: { chave: "campo-de-areia", rotulo: "Campo de areia" },
  115: { chave: "valor-medida", rotulo: "Valor medida" },
  116: { chave: "canil", rotulo: "Canil" },
  117: { chave: "capela", rotulo: "Capela" },
  118: { chave: "casa-empregado", rotulo: "Casa empregado" },
  119: { chave: "casa-sede", rotulo: "Casa sede" },
  120: { chave: "cerca", rotulo: "Cerca" },
  121: { chave: "cerca-viva", rotulo: "Cerca viva" },
  122: { chave: "como-chegar", rotulo: "Como chegar" },
  123: { chave: "distancia-asfalto", rotulo: "Distância asfalto" },
  124: { chave: "distancia-terra", rotulo: "Distância terra" },
  125: { chave: "estabulo", rotulo: "Estábulo" },
  126: { chave: "finalidade", rotulo: "Finalidade" },
  127: { chave: "galpao", rotulo: "Galpão" },
  128: { chave: "granja", rotulo: "Granja" },
  129: { chave: "gramada", rotulo: "Gramada" },
  130: { chave: "lago", rotulo: "Lago" },
  131: { chave: "lagoa", rotulo: "Lagoa" },
  132: { chave: "magueiro", rotulo: "Magueiro" },
  133: { chave: "nome-da-propriedade", rotulo: "Nome da propriedade" },
  134: { chave: "plantacao", rotulo: "Plantação" },
  135: { chave: "plantacao-outros", rotulo: "Plantação Outros" },
  136: { chave: "pocilga", rotulo: "Pocilga" },
  137: { chave: "poco-artesiano", rotulo: "Poço artesiano" },
  138: { chave: "poco-cacimba", rotulo: "Poço caçimba" },
  139: { chave: "pomar", rotulo: "Pomar" },
  140: { chave: "represa", rotulo: "Represa" },
  141: { chave: "tipo-de-terra", rotulo: "Tipo de terra" },
  142: { chave: "topografia", rotulo: "Topografia" },
  143: { chave: "pomar-outros", rotulo: "Pomar Outros" },
  144: { chave: "asfalto", rotulo: "Asfalto" },
  145: { chave: "calcada", rotulo: "Calçada" },
  146: { chave: "construcao", rotulo: "Construção" },
  147: { chave: "saneamento-basico", rotulo: "Saneamento Básico" },
  148: { chave: "esquina", rotulo: "Esquina" },
  149: { chave: "iluminacao", rotulo: "Iluminação" },
  150: { chave: "isolado", rotulo: "Isolado" },
  151: { chave: "lote", rotulo: "Lote" },
  152: { chave: "quadra", rotulo: "Quadra" },
  153: { chave: "recuo", rotulo: "Recuo" },
  154: { chave: "edicula", rotulo: "Edícula" },
  155: { chave: "edicula-dormitorios", rotulo: "Edícula Dormitórios" },
  156: { chave: "edicula-suites", rotulo: "Edícula Suítes" },
  157: { chave: "edicula-banheiros", rotulo: "Edícula Banheiros" },
  158: { chave: "tirolesa", rotulo: "Tirolesa" },
  159: { chave: "tipo-garagens", rotulo: "Tipo garagens" },
  160: { chave: "observacao-garagens", rotulo: "Observação garagens" },
  161: { chave: "more-de-graca", rotulo: "More de graça" },
  162: { chave: "concertina", rotulo: "Concertina" },
  163: { chave: "valor-do-condominio-no-emprendimento", rotulo: "Valor do condomínio no emprendimento" },
  164: { chave: "medida-lado-tres", rotulo: "Medida lado tres" },
  165: { chave: "medida-lado-quatro", rotulo: "Medida lado quatro" },
  166: { chave: "escritorio", rotulo: "Escritório" },
  167: { chave: "despejo", rotulo: "Despejo" },
  169: { chave: "alarme", rotulo: "Alarme" },
  170: { chave: "quintal", rotulo: "Quintal" },
  171: { chave: "quintal-com-grama", rotulo: "Quintal com grama" },
  172: { chave: "medida-distancia-asfalto", rotulo: "Medida distância asfalto" },
  173: { chave: "medida-distancia-terra", rotulo: "Medida distância terra" },
  174: { chave: "edicula-cozinha", rotulo: "Edícula Cozinha" },
  175: { chave: "edicula-sala", rotulo: "Edícula Sala" },
  176: { chave: "total-de-banheiros", rotulo: "Total de Banheiros" },
  177: { chave: "pagamento-a-vista", rotulo: "Pagamento á Vista" },
  178: { chave: "teto-em-madeira", rotulo: "Teto em madeira" },
  179: { chave: "tipo-de-piso", rotulo: "Tipo de piso" },
  180: { chave: "armarios-na-cozinha", rotulo: "Armários na Cozinha" },
  181: { chave: "armarios-no-quarto", rotulo: "Armários no Quarto" },
  182: { chave: "armarios-nos-banheiros", rotulo: "Armários nos Banheiros" },
  183: { chave: "cama-de-casal", rotulo: "Cama de casal" },
  184: { chave: "cama-de-solteiro", rotulo: "Cama de solteiro" },
  185: { chave: "espelho-no-banheiro", rotulo: "Espelho no banheiro" },
  186: { chave: "mesa-e-cadeiras", rotulo: "Mesa e cadeiras" },
  187: { chave: "sofa", rotulo: "Sofá" },
  188: { chave: "televisao", rotulo: "Televisão" },
  189: { chave: "utensilios-de-cozinha", rotulo: "Utensílios de cozinha" },
  190: { chave: "sol-da-manha", rotulo: "Sol da manhã" },
  191: { chave: "sol-da-tarde", rotulo: "Sol da tarde" },
  192: { chave: "acesso-sem-degraus", rotulo: "Acesso sem degraus" },
  193: { chave: "vista-livre", rotulo: "Vista livre" },
  194: { chave: "aceita-pet", rotulo: "Aceita pet" },
  195: { chave: "brinquedoteca", rotulo: "Brinquedoteca" },
  196: { chave: "cinema", rotulo: "Cinema" },
  197: { chave: "deck-de-madeira", rotulo: "Deck de madeira" },
  198: { chave: "deck-molhado", rotulo: "Deck Molhado" },
  199: { chave: "manobrista", rotulo: "Manobrista" },
  200: { chave: "piscina-aquecida", rotulo: "Piscina Aquecida" },
  201: { chave: "pista-para-caminhada", rotulo: "Pista para caminhada" },
  202: { chave: "playground", rotulo: "Playground" },
  203: { chave: "portaria-blindada", rotulo: "Portaria blindada" },
  204: { chave: "portaria-virtual", rotulo: "Portaria virtual" },
  205: { chave: "salao-de-jogos", rotulo: "Salão de Jogos" },
  206: { chave: "spa", rotulo: "SPA" },
  207: { chave: "quadra-de-beach-tenis", rotulo: "Quadra de Beach Tênis" },
  208: { chave: "redario", rotulo: "Redário" },
  209: { chave: "sala-de-reunioes", rotulo: "Sala de reuniões" },
  210: { chave: "porteiro-eletronico", rotulo: "Porteiro eletrônico" },
  211: { chave: "observacao-permuta", rotulo: "Observação Permuta" },
  212: { chave: "acesso-para-deficientes", rotulo: "Acesso para deficientes" },
  213: { chave: "atelier", rotulo: "Atelier" },
  214: { chave: "camareira", rotulo: "Camareira" },
  215: { chave: "espaco-kids", rotulo: "Espaço Kids" },
  216: { chave: "estacionamento-externo", rotulo: "Estacionamento externo" },
  217: { chave: "estacionamento-interno", rotulo: "Estacionamento interno" },
  218: { chave: "gas-encanado", rotulo: "Gás encanado" },
  219: { chave: "infraestrutura-completa", rotulo: "Infraestrutura completa" },
  220: { chave: "jacuzzi-no-terraco", rotulo: "Jacuzzi no terraço" },
  222: { chave: "mezanino", rotulo: "Mezanino" },
  223: { chave: "padaria", rotulo: "Padaria" },
  224: { chave: "pet-place", rotulo: "Pet Place" },
  225: { chave: "praca", rotulo: "Praça" },
  226: { chave: "sala-de-estudo", rotulo: "Sala de estudo" },
  227: { chave: "salao-de-beleza", rotulo: "Salão de beleza" },
  228: { chave: "sauna-umida", rotulo: "Sauna úmida" },
  229: { chave: "solarium", rotulo: "Solarium" },
  230: { chave: "terraco-grill", rotulo: "Terraço Grill" },
  231: { chave: "apartamento-andar-alto", rotulo: "Apartamento Andar Alto" },
  232: { chave: "ar-condicionado", rotulo: "Ar-condicionado" },
  233: { chave: "casa-terrea", rotulo: "Casa Térrea" },
  234: { chave: "area-de-servico", rotulo: "Área de serviço" },
  235: { chave: "sacada", rotulo: "Sacada" },
  236: { chave: "quantidade-garagens", rotulo: "Quantidade garagens" },
  237: { chave: "observacoes-garagens", rotulo: "Observações garagens" },
  239: { chave: "preco-por-alqueire", rotulo: "Preço por alqueire" },
  240: { chave: "mangueiro", rotulo: "Mangueiro" },
  241: { chave: "outras-benfeitorias", rotulo: "Outras benfeitorias" },
  242: { chave: "cercada", rotulo: "Cercada" },
  243: { chave: "individual", rotulo: "Individual" },
  244: { chave: "independente", rotulo: "Independente" },
  245: { chave: "geladeira", rotulo: "Geladeira" },
  246: { chave: "cooktop", rotulo: "Cooktop" },
  247: { chave: "fogao", rotulo: "Fogão" },
  248: { chave: "ventilador", rotulo: "Ventilador" },
  249: { chave: "mini-quadra", rotulo: "Mini quadra" },
  250: { chave: "espaco-jovem", rotulo: "Espaço jovem" },
  251: { chave: "bosque", rotulo: "Bosque" },
  252: { chave: "churrasqueira-com-forno-de-pizza", rotulo: "Churrasqueira com forno de pizza" },
  253: { chave: "pet-care", rotulo: "Pet care" },
  254: { chave: "aquecedor-solar", rotulo: "Aquecedor solar" },
  255: { chave: "jardim", rotulo: "Jardim" },
  256: { chave: "jardim-de-inverno", rotulo: "Jardim de inverno" },
  257: { chave: "wc-adaptado", rotulo: "WC adaptado" },
  258: { chave: "wc-fundos", rotulo: "WC fundos" },
  259: { chave: "hidro", rotulo: "Hidro" },
  260: { chave: "piscina-coberta", rotulo: "Piscina coberta" },
  261: { chave: "piscina-coberta-com-raia", rotulo: "Piscina coberta com raia" },
  262: { chave: "coworking", rotulo: "Coworking" },
  263: { chave: "lareira", rotulo: "Lareira" },
  264: { chave: "lareira-a-gas", rotulo: "Lareira à gás" },
  265: { chave: "lareira-ecologica", rotulo: "Lareira ecológica" },
  266: { chave: "churrasqueira-a-gas", rotulo: "Churrasqueira à gás" },
  267: { chave: "horta", rotulo: "Horta" },
  268: { chave: "bicicletario", rotulo: "Bicicletário" },
  269: { chave: "fraldario", rotulo: "Fraldário" },
  270: { chave: "lago-de-pesca", rotulo: "Lago de pesca" },
  271: { chave: "cabeamento-subterraneo", rotulo: "Cabeamento subterrâneo" },
  272: { chave: "heliponto", rotulo: "Heliponto" },
  273: { chave: "bosque-privativo-de-app", rotulo: "Bosque Privativo de APP" },
  274: { chave: "campo-de-golf", rotulo: "Campo de Golf" },
  275: { chave: "praia-artificial", rotulo: "Praia artificial" },
  276: { chave: "hipica", rotulo: "Hípica" },
  277: { chave: "pista-de-skate", rotulo: "Pista de Skate" },
  278: { chave: "ofuro", rotulo: "Ofurô" },
  279: { chave: "area-privativa", rotulo: "Área privativa" },
  280: { chave: "porcelanato", rotulo: "Porcelanato" },
  281: { chave: "paisagismo", rotulo: "Paisagismo" },
  282: { chave: "encanamento-para-aquecedor", rotulo: "Encanamento para aquecedor" },
  283: { chave: "varanda", rotulo: "Varanda" },
  284: { chave: "vista-mar", rotulo: "Vista mar" },
  285: { chave: "aquecimento-eletrico", rotulo: "Aquecimento elétrico" },
  286: { chave: "aquecimento-a-gas", rotulo: "Aquecimento a gás" },
  287: { chave: "casa-para-caseiro", rotulo: "Casa para caseiro" },
  288: { chave: "casa-de-hospedes", rotulo: "Casa de hóspedes" },
  289: { chave: "doca", rotulo: "Doca" },
  290: { chave: "energia-para-carro-eletrico", rotulo: "Energia para carro elétrico" },
  291: { chave: "esgoto", rotulo: "Esgoto" },
  292: { chave: "fossa", rotulo: "Fossa" },
  293: { chave: "gerador-de-energia-solar", rotulo: "Gerador de energia solar" },
  294: { chave: "piscina-com-aquecimento-solar", rotulo: "Piscina com aquecimento solar" },
  295: { chave: "poco-semi-artesiano", rotulo: "Poço semi-artesiano" },
  296: { chave: "sistema-de-seguranca", rotulo: "Sistema de segurança" },
  297: { chave: "armario-no-espaco-gourmet", rotulo: "Armário no espaço gourmet" },
  298: { chave: "armario-no-closet", rotulo: "Armário no closet" },
  299: { chave: "armario-na-sala", rotulo: "Armário na sala" },
  300: { chave: "armario-na-area-de-servico", rotulo: "Armário na área de serviço" },
  301: { chave: "armario-no-escritorio", rotulo: "Armário no escritório" },
  302: { chave: "box-nos-banheiros", rotulo: "Box nos banheiros" },
  303: { chave: "coifa", rotulo: "Coifa" },
  304: { chave: "cortina", rotulo: "Cortina" },
  305: { chave: "persiana", rotulo: "Persiana" },
  306: { chave: "cabine-para-geradores", rotulo: "Cabine para Geradores" },
  307: { chave: "cartao-de-carrinho-de-supermercado", rotulo: "Cartão de carrinho de supermercado" },
  308: { chave: "clube", rotulo: "Clube" },
  309: { chave: "portao-eletronico-para-pedestre", rotulo: "Portão eletrônico para pedestre" },
  310: { chave: "estacionamento-para-visitante", rotulo: "Estacionamento para visitante" },
  311: { chave: "iluminacao-publica", rotulo: "Iluminação Pública" },
  312: { chave: "portaria-digital", rotulo: "Portaria Digital" },
  313: { chave: "recepcao", rotulo: "Recepção" },
  314: { chave: "seguranca-motorizada", rotulo: "Segurança Motorizada" },
  315: { chave: "agua-encanada", rotulo: "Água encanada" },
  316: { chave: "ano-de-construcao", rotulo: "Ano de Construção" },
  317: { chave: "acesso-24-hrs", rotulo: "Acesso 24 Hrs" },
  318: { chave: "acesso-a-linha-ferrea", rotulo: "Acesso a linha férrea" },
  319: { chave: "adega", rotulo: "Adega" },
  320: { chave: "administradora", rotulo: "Administradora" },
  321: { chave: "almoxarifado", rotulo: "Almoxarifado" },
  322: { chave: "aquecedor", rotulo: "Aquecedor" },
  323: { chave: "aquecimento", rotulo: "Aquecimento" },
  324: { chave: "area-de-estar-externa", rotulo: "Área de estar externa" },
  325: { chave: "area-verde", rotulo: "Área verde" },
  326: { chave: "baby-child-care", rotulo: "Baby child care" },
  327: { chave: "baby-place-com-fraldario", rotulo: "Baby place com fraldário" },
  328: { chave: "baby-space", rotulo: "Baby space" },
  329: { chave: "bangolo", rotulo: "Bangolo" },
  330: { chave: "banheira", rotulo: "Banheira" },
  331: { chave: "bar", rotulo: "Bar" },
  332: { chave: "bar-molhado", rotulo: "Bar molhado" },
  333: { chave: "biblioteca", rotulo: "Biblioteca" },
  334: { chave: "bike-indoor", rotulo: "Bike indoor" },
  335: { chave: "biribol", rotulo: "Biribol" },
  336: { chave: "body-center", rotulo: "Body center" },
  337: { chave: "boxe", rotulo: "Boxe" },
  338: { chave: "business-center", rotulo: "Business center" },
  339: { chave: "caminho-dos-bambus", rotulo: "Caminho dos bambus" },
  340: { chave: "car-wash", rotulo: "Car wash" },
  341: { chave: "carpete", rotulo: "Carpete" },
  342: { chave: "casa-de-fundo", rotulo: "Casa de fundo" },
  343: { chave: "caseiro", rotulo: "Caseiro" },
  344: { chave: "central-telefonica", rotulo: "Central telefônica" },
  345: { chave: "centro-de-estetica", rotulo: "Centro de estética" },
  346: { chave: "child-care", rotulo: "Child care" },
  347: { chave: "circuito-de-televisao", rotulo: "Circuito de televisão" },
  348: { chave: "claraboia", rotulo: "Clarabóia" },
  349: { chave: "coffee-shop", rotulo: "Coffee shop" },
  350: { chave: "condominio-fechado", rotulo: "Condominio fechado" },
  351: { chave: "cozinha-americana", rotulo: "Cozinha americana" },
  352: { chave: "cozinha-gourmet", rotulo: "Cozinha gourmet" },
  353: { chave: "cozinha-independente", rotulo: "Cozinha independente" },
  354: { chave: "dependencia-de-empregados", rotulo: "Dependencia de empregados" },
  355: { chave: "deposito-privativo", rotulo: "Depósito privativo" },
  356: { chave: "deposito-subsolo", rotulo: "Deposito subsolo" },
  357: { chave: "descanso", rotulo: "Descanso" },
  358: { chave: "ducha", rotulo: "Ducha" },
  359: { chave: "elevador-com-senha", rotulo: "Elevador com senha" },
  360: { chave: "energia-eletrica", rotulo: "Energia elétrica" },
  361: { chave: "entrada-de-caminhoes", rotulo: "Entrada de caminhões" },
  362: { chave: "entrada-de-servico-independente", rotulo: "Entrada de serviço independente" },
  363: { chave: "entrada-facilitada", rotulo: "Entrada facilitada" },
  364: { chave: "entrada-lateral", rotulo: "Entrada lateral" },
  365: { chave: "escritorio-virtual", rotulo: "Escritório virtual" },
  366: { chave: "espaco-circo", rotulo: "Espaço circo" },
  367: { chave: "espaco-cultural", rotulo: "Espaço cultural" },
  368: { chave: "espaco-mulher", rotulo: "Espaço mulher" },
  369: { chave: "espaco-zen", rotulo: "Espaço zen" },
  370: { chave: "estacionamento", rotulo: "Estacionamento" },
  371: { chave: "estacionamento-coberto", rotulo: "Estacionamento coberto" },
  372: { chave: "estacionamento-rotativo", rotulo: "Estacionamento rotativo" },
  373: { chave: "estar-junto-ao-lazer-interno", rotulo: "Estar junto ao lazer interno" },
  374: { chave: "estar-na-agua", rotulo: "Estar na água" },
  375: { chave: "estrada-ou-rua-asfaltada", rotulo: "Estrada ou rua asfaltada" },
  376: { chave: "fitness-ao-ar-livre", rotulo: "Fitness ao ar livre" },
  377: { chave: "forno-a-lenha", rotulo: "Forno a lenha" },
  378: { chave: "forno-de-pizza", rotulo: "Forno de pizza" },
  379: { chave: "forro", rotulo: "Forro" },
  380: { chave: "freezer", rotulo: "Freezer" },
  381: { chave: "game-station", rotulo: "Game station" },
  382: { chave: "garage-band", rotulo: "Garage band" },
  383: { chave: "garagem", rotulo: "Garagem" },
  384: { chave: "garagem-descoberta", rotulo: "Garagem descoberta" },
  385: { chave: "garagem-independente", rotulo: "Garagem independente" },
  386: { chave: "gas-natural", rotulo: "Gás natural" },
  387: { chave: "geminada", rotulo: "Geminada" },
  388: { chave: "guarita", rotulo: "Guarita" },
  389: { chave: "home-office", rotulo: "Home office" },
  390: { chave: "home-theater", rotulo: "Home theater" },
  391: { chave: "infra-internet", rotulo: "Infra internet" },
  392: { chave: "internet", rotulo: "Internet" },
  393: { chave: "internet-compartilhada", rotulo: "Internet compartilhada" },
  394: { chave: "internet-wireless", rotulo: "Internet wireless" },
  395: { chave: "jacuzzi", rotulo: "Jacuzzi" },
  396: { chave: "jardim-ornamental", rotulo: "Jardim ornamental" },
  397: { chave: "lan-house", rotulo: "Lan house" },
  398: { chave: "lobby-com-pe-direito-duplo", rotulo: "Lobby com pé direito duplo" },
  399: { chave: "lounge", rotulo: "Lounge" },
  400: { chave: "lounge-com-lareira", rotulo: "Lounge com lareira" },
  401: { chave: "lustres", rotulo: "Lustres" },
  402: { chave: "marina", rotulo: "Marina" },
  403: { chave: "massagem", rotulo: "Massagem" },
  404: { chave: "mini-arvorismo", rotulo: "Mini arvorismo" },
  405: { chave: "orquidario", rotulo: "Orquidário" },
  406: { chave: "parque", rotulo: "Parque" },
  407: { chave: "patio-estacionamento", rotulo: "Patio estacionamento" },
  408: { chave: "pergolado", rotulo: "Pergolado" },
  409: { chave: "personal-training", rotulo: "Personal training" },
  410: { chave: "perto-de-escolas", rotulo: "Perto de escolas" },
  411: { chave: "perto-de-shopping-center", rotulo: "Perto de shopping center" },
  412: { chave: "perto-de-transporte-publico", rotulo: "Perto de transporte público" },
  413: { chave: "perto-de-vias-de-acesso", rotulo: "Perto de vias de acesso" },
  414: { chave: "pesqueiro", rotulo: "Pesqueiro" },
  415: { chave: "pet-play", rotulo: "Pet play" },
  416: { chave: "piano-bar", rotulo: "Piano bar" },
  417: { chave: "piscina-climatizada", rotulo: "Piscina climatizada" },
  418: { chave: "piscina-coberta-climatizada", rotulo: "Piscina coberta climatizada" },
  419: { chave: "piscina-com-hidromassagem", rotulo: "Piscina com hidromassagem" },
  420: { chave: "piscina-com-raia", rotulo: "Piscina com raia" },
  421: { chave: "piscina-ozonizada", rotulo: "Piscina ozonizada" },
  422: { chave: "piscina-raia-25m", rotulo: "Piscina raia 25M" },
  423: { chave: "piscina-semi-coberta", rotulo: "Piscina semi coberta" },
  424: { chave: "piso-de-madeira", rotulo: "Piso de madeira" },
  425: { chave: "piso-elevado", rotulo: "Piso elevado" },
  426: { chave: "piso-frio", rotulo: "Piso frio" },
  427: { chave: "piso-laminado", rotulo: "Piso laminado" },
  428: { chave: "pista-cooper", rotulo: "Pista cooper" },
  429: { chave: "pista-de-atletismo", rotulo: "Pista de atletismo" },
  430: { chave: "pista-de-patinacao", rotulo: "Pista de patinação" },
  431: { chave: "playground-baby", rotulo: "Playground baby" },
  432: { chave: "playground-junior", rotulo: "Playground junior" },
  433: { chave: "porao", rotulo: "Porão" },
  434: { chave: "port-cochere", rotulo: "Port cochere" },
  435: { chave: "portaria-12hrs", rotulo: "Portaria 12HRS" },
  436: { chave: "portaria-ou-catraca", rotulo: "Portaria ou catraca" },
  437: { chave: "posto-bancario", rotulo: "Posto bancário" },
  438: { chave: "proximo-a-hospitais", rotulo: "Próximo a hospitais" },
  439: { chave: "proximo-ao-metro", rotulo: "Próximo ao metrô" },
  440: { chave: "pub", rotulo: "Pub" },
  441: { chave: "quadra-de-futsal", rotulo: "Quadra de futsal" },
  442: { chave: "quadra-de-society", rotulo: "Quadra de society" },
  443: { chave: "quadra-de-squash", rotulo: "Quadra de squash" },
  444: { chave: "quadra-de-volei-de-praia", rotulo: "Quadra de vôlei de praia" },
  445: { chave: "quadra-recreativa", rotulo: "Quadra recreativa" },
  446: { chave: "quiosque-com-churrasqueira-e-forno", rotulo: "Quiosque com churrasqueira e forno" },
  447: { chave: "rede-telefone", rotulo: "Rede telefone" },
  448: { chave: "refeitorio", rotulo: "Refeitório" },
  449: { chave: "reservatorio-de-agua", rotulo: "Reservatório de água" },
  450: { chave: "restaurante", rotulo: "Restaurante" },
  451: { chave: "saida-de-emergencia", rotulo: "Saída de emergência" },
  452: { chave: "sala-de-almoco", rotulo: "Sala de almoço" },
  453: { chave: "sala-de-conferencia", rotulo: "Sala de conferência" },
  454: { chave: "sala-de-convencoes", rotulo: "Sala de convenções" },
  455: { chave: "sala-de-estar", rotulo: "Sala de estar" },
  456: { chave: "sala-de-ginastica", rotulo: "Sala de ginástica" },
  457: { chave: "sala-de-jantar", rotulo: "Sala de jantar" },
  458: { chave: "sala-de-leitura", rotulo: "Sala de leitura" },
  459: { chave: "sala-de-massagem", rotulo: "Sala de massagem" },
  460: { chave: "sala-de-tv", rotulo: "Sala de TV" },
  461: { chave: "sala-de-yoga", rotulo: "Sala de yoga" },
  462: { chave: "salao-gourmet", rotulo: "Salão gourmet" },
  463: { chave: "seguranca", rotulo: "Segurança" },
  464: { chave: "seguranca-24-horas", rotulo: "Segurança 24 Horas" },
  465: { chave: "seguranca-na-rua", rotulo: "Segurança na rua" },
  466: { chave: "seguranca-patrimonial", rotulo: "Segurança patrimonial" },
  467: { chave: "semi-mobiliado", rotulo: "Semi mobiliado" },
  468: { chave: "servicos", rotulo: "Serviços" },
  469: { chave: "servicos-de-escritorio", rotulo: "Serviços de escritório" },
  470: { chave: "servicos-pay-per-use", rotulo: "Serviços pay-per-use" },
  471: { chave: "servicos-publicos-essenciais", rotulo: "Serviços públicos essenciais" },
  472: { chave: "sistema-de-incendio", rotulo: "Sistema de incêndio" },
  473: { chave: "sotao", rotulo: "Sotão" },
  474: { chave: "spa-com-sauna-e-ofuro", rotulo: "Spa com sauna e ofurô" },
  475: { chave: "sprinklers-contra-incendio", rotulo: "Sprinklers contra incêndio" },
  476: { chave: "telefone", rotulo: "Telefone" },
  477: { chave: "televisao-a-cabo", rotulo: "Televisão a cabo" },
  478: { chave: "terraco", rotulo: "Terraço" },
  479: { chave: "terraco-gourmet", rotulo: "Terraço gourmet" },
  480: { chave: "teto-rebaixado", rotulo: "Teto rebaixado" },
  481: { chave: "trilha-na-mata-com-redario", rotulo: "Trilha na mata com redário" },
  482: { chave: "vestiario-para-empregados", rotulo: "Vestiário para empregados" },
  483: { chave: "vigilancia-24-horas", rotulo: "Vigilância 24 horas" },
  484: { chave: "vista-exterior", rotulo: "Vista exterior" },
  485: { chave: "vista-para-a-montanha", rotulo: "Vista para a montanha" },
  486: { chave: "web-space", rotulo: "Web space" },
  487: { chave: "forno", rotulo: "Forno" },
  488: { chave: "micro-ondas", rotulo: "Micro-ondas" },
  489: { chave: "energia-fotovoltaica", rotulo: "Energia fotovoltaica" },
  490: { chave: "casa-de-hospedes", rotulo: "Casa de hóspedes" },
  491: { chave: "frente-norte", rotulo: "Frente norte" },
  492: { chave: "frente-sul", rotulo: "Frente sul" },
  493: { chave: "frente-leste", rotulo: "Frente leste" },
  494: { chave: "frente-oeste", rotulo: "Frente oeste" },
  495: { chave: "portaria-horario-comercial", rotulo: "Portaria horário comercial" },
  496: { chave: "churrasqueira", rotulo: "Churrasqueira" },
  497: { chave: "lounge-bar", rotulo: "Lounge bar" },
  498: { chave: "praca-do-cochilo", rotulo: "Praça do cochilo" },
  499: { chave: "praca-da-fogueira", rotulo: "Praça da fogueira" },
  500: { chave: "praca-da-saude", rotulo: "Praça da saúde" },
  501: { chave: "exaustor", rotulo: "Exaustor" },
  502: { chave: "exaustor", rotulo: "Exaustor" },
  503: { chave: "micro-ondas", rotulo: "Micro-ondas" },
  504: { chave: "maquina-de-lavar", rotulo: "Máquina de lavar" },
  505: { chave: "frigobar", rotulo: "Frigobar" },
  506: { chave: "guarda-roupa", rotulo: "Guarda-Roupa" },
  507: { chave: "guarda-roupa-tipo-closet", rotulo: "Guarda-Roupa tipo closet" },
  508: { chave: "escrivaninha", rotulo: "Escrivaninha" },
  509: { chave: "mesa-redonda-com-cadeira", rotulo: "Mesa redonda com cadeira" },
  510: { chave: "fogao-eletrico-2-bocas", rotulo: "Fogão elétrico 2 bocas" },
  511: { chave: "chuveiro-220v", rotulo: "Chuveiro 220v" },
  512: { chave: "cama-box-com-colchao", rotulo: "Cama box com colchão" },
  513: { chave: "cortina-blackout", rotulo: "Cortina blackout" },
  514: { chave: "cama-sofa", rotulo: "Cama sofá" },
  515: { chave: "portaria-com-reconhecimento-facial", rotulo: "Portaria com reconhecimento facial" },
  516: { chave: "coleta-seletiva", rotulo: "Coleta seletiva" },
  517: { chave: "horta-comunitaria", rotulo: "Horta comunitária" },
  518: { chave: "area-gourmet-burguer", rotulo: "Area gourmet burguer" },
  519: { chave: "area-gourmet-pizza", rotulo: "Area gourmet pizza" },
  520: { chave: "area-de-lazer-equipadas-completas", rotulo: "Area de lazer equipadas completas" },
  521: { chave: "playground-wi-fi-nas-areas-comuns", rotulo: "Playground - Wi-fi nas áreas comuns" },
  522: { chave: "tomadas-usb-nas-areas-comuns", rotulo: "Tomadas USB nas áreas comuns" },
  523: { chave: "medicao-de-agua-individualizada", rotulo: "Medição de água individualizada" },
  524: { chave: "medidores-de-energia-individuais", rotulo: "Medidores de energia individuais" },
  525: { chave: "dispositivos-economizadores-de-agua", rotulo: "Dispositivos economizadores de água" },
  526: { chave: "gerador-de-conforto", rotulo: "Gerador de Conforto" },
  527: { chave: "conveniencia", rotulo: "Conveniência" },
  528: { chave: "salas-de-reunioes", rotulo: "Salas de reuniões" },
  529: { chave: "cafeteria", rotulo: "Cafeteria" },
  530: { chave: "quiosque", rotulo: "Quiosque" },
  531: { chave: "guarita-blindada", rotulo: "Guarita Blindada" },
  532: { chave: "churrasqueira-na-varanda", rotulo: "Churrasqueira na Varanda" },
  533: { chave: "armario-embutido", rotulo: "Armário embutido" },
  534: { chave: "fechadura-digital", rotulo: "Fechadura digital" },
  535: { chave: "condominio-sustentavel", rotulo: "Condomínio sustentável" },
  536: { chave: "carregador-eletronico-para-carro-e-bicicleta", rotulo: "Carregador eletrônico para carro e bicicleta" },
  537: { chave: "cabeamento-estruturado", rotulo: "Cabeamento estruturado" },
  538: { chave: "gerador-eletrico", rotulo: "Gerador elétrico" },
  539: { chave: "cascalho", rotulo: "Cascalho" },
  540: { chave: "ambientes-integrados", rotulo: "Ambientes integrados" },
  541: { chave: "vista-para-lago", rotulo: "Vista para lago" },
  542: { chave: "terra", rotulo: "Terra" },
  543: { chave: "cozinha-grande", rotulo: "Cozinha grande" },
  544: { chave: "janela-grande", rotulo: "Janela grande" },
  545: { chave: "mais-de-um-andar", rotulo: "Mais de um andar" },
  546: { chave: "ronda-vigilancia", rotulo: "Ronda/Vigilância" },
  547: { chave: "apartamento-inteligente", rotulo: "Apartamento inteligente" },
  548: { chave: "condominio-inteligente", rotulo: "Condomínio inteligente" },
  549: { chave: "loja", rotulo: "Loja" },
  550: { chave: "publicos-essenciais", rotulo: "Públicos essenciais" },
  551: { chave: "escada", rotulo: "Escada" },
  552: { chave: "piscina-semi-olimpica", rotulo: "Piscina semi-olímpica" },
  553: { chave: "controlador-de-acesso", rotulo: "Controlador de acesso" },
  554: { chave: "persiana-motorizada", rotulo: "Persiana motorizada" },
  555: { chave: "iluminacao-automatizada", rotulo: "Iluminação automatizada" },
  556: { chave: "irrigacao-automatizada", rotulo: "Irrigação automatizada" },
  557: { chave: "sistema-eletrico-anti-surto", rotulo: "Sistema elétrico anti surto" },
  558: { chave: "tomada-eletrica-para-todas-as-vagas-de-garagem", rotulo: "Tomada elétrica para todas as vagas de garagem" },
  559: { chave: "elevador-com-biotracking-em-aco-escovado-em-todos-os-pavimentos", rotulo: "Elevador com biotracking em aço escovado em todos os pavimentos" },
  560: { chave: "sala-para-motoristas-e-segurancas-particulares", rotulo: "Sala para motoristas e seguranças particulares" },
  561: { chave: "internet-wireless-condominio-nas-areas-de-lazer", rotulo: "Internet wireless condomínio nas áreas de lazer" },
  562: { chave: "portao-automatico-com-sistema-de-leitura-de-placa-nas-garagens", rotulo: "Portão automático com sistema de leitura de placa nas garagens" },
  563: { chave: "infraestrutura-de-controle-de-acessos-e-monitoramento-por-aplicativo-em-todo-o-empreendimento", rotulo: "Infraestrutura de controle de acessos e monitoramento por aplicativo em todo o empreendimento" },
  564: { chave: "porta-com-guilhotina-e-vedacao-na-entrada-dos-apartamentos", rotulo: "Porta com guilhotina e vedação na entrada dos apartamentos" },
  565: { chave: "infraestrutura-para-automacao", rotulo: "Infraestrutura para automação" },
  566: { chave: "porta-principal-com-fechadura-eletronica", rotulo: "Porta principal com fechadura eletrônica" },
  567: { chave: "esquadrias-linha-gold-30mm-com-vidro-duplo-nas-esquadrias-dos-dormitorios", rotulo: "Esquadrias linha gold - 30mm com vidro duplo nas esquadrias dos dormitórios" },
  568: { chave: "manta-de-isolamento-acustico-entre-os-apartamentos-parede-piso-teto", rotulo: "Manta de isolamento acústico entre os apartamentos(Parede, Piso, Teto)" },
  569: { chave: "rooftop", rotulo: "Rooftop" },
  570: { chave: "hall-de-entrada-decorado-e-mobiliado", rotulo: "Hall de entrada decorado e mobiliado" },
  571: { chave: "piscina-adulto", rotulo: "Piscina adulto" },
  572: { chave: "piscina-adulto-com-borda-infinita", rotulo: "Piscina adulto com borda infinita" },
  573: { chave: "bar-seco", rotulo: "Bar seco" },
  574: { chave: "prainha", rotulo: "Prainha" },
  575: { chave: "piscina-coberta-aquecida", rotulo: "Piscina coberta aquecida" },
  576: { chave: "piscina-externa", rotulo: "Piscina externa" },
  577: { chave: "splash", rotulo: "Splash" },
  578: { chave: "lounge-piscina-fireplace", rotulo: "Lounge Piscina/Fireplace" },
  579: { chave: "salao-de-festas-1", rotulo: "Salão de festas 1" },
  580: { chave: "salao-de-festas-2", rotulo: "Salão de festas 2" },
  581: { chave: "lounge-salao-de-festas-1", rotulo: "Lounge Salão de festas 1" },
  582: { chave: "lounge-salao-de-festas-2", rotulo: "Lounge Salão de festas 2" },
  583: { chave: "fireplace-garden", rotulo: "Fireplace Garden" },
  584: { chave: "lavanderia-compartilhada", rotulo: "Lavanderia compartilhada" },
  585: { chave: "bar-piscina", rotulo: "Bar piscina" },
  586: { chave: "teems", rotulo: "Teems" },
  587: { chave: "spas-frente-mar", rotulo: "Spas frente mar" },
  588: { chave: "portaria-principal", rotulo: "Portaria principal" },
  589: { chave: "lava-pes", rotulo: "Lava pés" },
  590: { chave: "grad-e-go", rotulo: "Grad e Go" },
  591: { chave: "sala-delivery", rotulo: "Sala delivery" },
  592: { chave: "elevadores", rotulo: "Elevadores" },
  593: { chave: "copa-funcionarios", rotulo: "Copa Funcionários" },
  594: { chave: "zeladora-adm", rotulo: "Zeladora Adm" },
  595: { chave: "hobby-box", rotulo: "Hobby Box" },
  596: { chave: "vagas-para-as-lojas", rotulo: "Vagas para as Lojas" },
  597: { chave: "lojas", rotulo: "Lojas" },
  598: { chave: "mini-mercado", rotulo: "Mini Mercado" },
  599: { chave: "varanda-envidracada", rotulo: "Varanda Envidraçada" },
  600: { chave: "varanda-aberta", rotulo: "Varanda Aberta" },
  601: { chave: "acesso-para-pne", rotulo: "Acesso para PNE" },
  602: { chave: "banheiro-s-pne", rotulo: "Banheiro(s) PNE" },
  603: { chave: "elevador-es-de-acesso-pne", rotulo: "Elevador(es) de acesso PNE" },
  604: { chave: "biometria", rotulo: "Biometria" },
  605: { chave: "moveis-planejados-na-sala", rotulo: "Móveis planejados na sala" },
  606: { chave: "moveis-planejados-na-cozinha", rotulo: "Móveis planejados na cozinha" },
  607: { chave: "moveis-planejados-no-banheiro", rotulo: "Móveis planejados no banheiro" },
  608: { chave: "moveis-planejados", rotulo: "Móveis Planejados" },
  609: { chave: "camarote", rotulo: "Camarote" },
  610: { chave: "palco", rotulo: "Palco" },
  611: { chave: "maquina-de-lavar-louca", rotulo: "Máquina de lavar louça" },
  612: { chave: "piso-vinilico", rotulo: "Piso Vinílico" },
  613: { chave: "rebaixamento-de-gesso", rotulo: "Rebaixamento de gesso" },
  614: { chave: "cisterna-para-captacao-de-agua-da-chuva", rotulo: "Cisterna para captação de água da chuva" },
  615: { chave: "sacada-com-churrasqueira", rotulo: "Sacada com churrasqueira" },
  616: { chave: "sacada-fechada-em-reiki", rotulo: "Sacada fechada em Reiki" },
  617: { chave: "sacada-integrada", rotulo: "Sacada integrada" },
  618: { chave: "demi-suites", rotulo: "Demi-suítes" },
  619: { chave: "workspace", rotulo: "Workspace" },
  620: { chave: "rooftop-fitness", rotulo: "Rooftop Fitness" },
  621: { chave: "nao-aceita-pet", rotulo: "Não aceita Pet" },
  622: { chave: "lavanderia-interna", rotulo: "Lavanderia interna" },
  624: { chave: "mesa-sem-cadeiras", rotulo: "Mesa sem cadeiras" },
  625: { chave: "painel-para-tv", rotulo: "Painel para TV" },
  626: { chave: "suite-master", rotulo: "Suíte Master" },
  627: { chave: "cortinas", rotulo: "Cortinas" },
  628: { chave: "forno-embutido", rotulo: "Forno embutido" },
  629: { chave: "tipos-de-forro", rotulo: "Tipos de forro" },
}

// ---- Curado à mão (preservado pelo gerador) ----
export interface CaracteristicaResolvida {
  chave: string
  rotulo: string
  grupo?: string
}

export const GRUPOS: Record<number, string> = {
  97: "elevador", 96: "elevador", 592: "elevador",
  15: "piscina", 571: "piscina", 73: "piscina", 572: "piscina",
  496: "churrasqueira", 17: "churrasqueira", 615: "churrasqueira",
  235: "sacada", 283: "sacada", 85: "sacada",
  76: "portaria", 312: "portaria", 204: "portaria", 515: "portaria",
}

export function resolverCaracteristica(idt: number): CaracteristicaResolvida | undefined {
  const base = ROTULOS[idt]
  if (!base) return undefined
  const grupo = GRUPOS[idt]
  return grupo ? { ...base, grupo } : { ...base }
}
